- name: service up
  hosts: all
  become: yes
  tasks:
    - name: stop tomcat
      service:
        name: tomcat
        state: stopped

    - name: start tomcat
      service:
        name: tomcat
        state: started
        
