- name: Service up
  hosts: all
  become: true
  tasks:
     - name: stop tomcat
      service:
        name: tomcat
        state: sttoped
        
    - name: stop docker
      service:
        name: docker
        start: sttoped
        
    - name: start tomcat
      service:
        name: tomcat
        state: started
        
    - name: start docker
      service:
        name: docker
        start: started
