- name: Service up
  hosts: all
  become: true
  tasks:
    - name: restart tomcat
      service:
        name: tomcat
        state: restarted
        
    - name: restart docker
      service:
        name: docker
        start: restarted
