- name: Service up
  hosts: all
  become: true
  tasks:
    - name: stop tomcat
      service:
        name: tomcat
        state: restarted
        
    - name: stop docker
      service:
        name: docker
        start: restarted
